export enum CustomerType {
  WHOLESALE = 'WHOLESALE',
  RETAIL = 'RETAIL',
}

export enum CustomerSegment {
  A = 'A',
  B = 'B',
  C = 'C',
  VIP = 'VIP',
  BLOCKED = 'BLOCKED',
}

export enum CustomerStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

export enum OrderType {
  WHOLESALE_PORTAL = 'WHOLESALE_PORTAL',
  WHOLESALE_PHONE = 'WHOLESALE_PHONE',
  WHOLESALE_FIELD = 'WHOLESALE_FIELD',
  WHOLESALE_TELEGRAM = 'WHOLESALE_TELEGRAM',
  RETAIL_WEBSITE = 'RETAIL_WEBSITE',
  MANUAL = 'MANUAL',
}

export enum OrderStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  PACKED = 'PACKED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  RETURN_REQUESTED = 'RETURN_REQUESTED',
  RETURN_APPROVED = 'RETURN_APPROVED',
  RETURNED = 'RETURNED',
  REFUNDED = 'REFUNDED',
}

export enum ProductStatus {
  DRAFT = 'DRAFT',
  ACTIVE = 'ACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  DISCONTINUED = 'DISCONTINUED',
  ARCHIVED = 'ARCHIVED',
  COMING_SOON = 'COMING_SOON',
}

export enum ProductSizeType {
  TWO = 'TWO',
  THREE = 'THREE',
  FREE = 'FREE',
}

export enum InvoiceType {
  PROFORMA = 'PROFORMA',
  FINAL = 'FINAL',
  CREDIT_NOTE = 'CREDIT_NOTE',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  OVERDUE = 'OVERDUE',
  VOIDED = 'VOIDED',
}

export enum PaymentGateway {
  ZARINPAL = 'ZARINPAL',
  IDPAY = 'IDPAY',
  MELLAT = 'MELLAT',
  SAMAN = 'SAMAN',
  PARSIAN = 'PARSIAN',
  BANK_TRANSFER = 'BANK_TRANSFER',
  COD = 'COD',
  SNAPPAY = 'SNAPPAY',
}

export enum PaymentMethod {
  ONLINE = 'ONLINE',
  BANK_TRANSFER = 'BANK_TRANSFER',
  COD = 'COD',
  CREDIT = 'CREDIT',
}

export enum ShippingMethod {
  CHAPAR = 'CHAPAR',
  POST = 'POST',
  PICKUP = 'PICKUP',
  LOCAL_MASHHAD = 'LOCAL_MASHHAD',
}

export enum UserRole {
  ADMIN = 'ADMIN',
  SALES_MANAGER = 'SALES_MANAGER',
  SALES_REP = 'SALES_REP',
  ACCOUNTANT = 'ACCOUNTANT',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  CUSTOMER_SERVICE = 'CUSTOMER_SERVICE',
}

export enum ReturnReason {
  WRONG_SIZE = 'WRONG_SIZE',
  WRONG_COLOR = 'WRONG_COLOR',
  QUALITY_DEFECT = 'QUALITY_DEFECT',
  DAMAGED_IN_SHIPPING = 'DAMAGED_IN_SHIPPING',
  NOT_AS_DESCRIBED = 'NOT_AS_DESCRIBED',
  CUSTOMER_CHANGED_MIND = 'CUSTOMER_CHANGED_MIND',
}

export type ProductSize = '38' | '40' | '42' | '44' | '46' | '48';

export const PRODUCT_SIZES: ProductSize[] = ['38', '40', '42', '44', '46', '48'];
